### PR TITLE
Fixes pfp issue on map page

### LINKED ISSUE #417: Profile image not showing on map view or allocation page
**Problem**
User updated profile image and profile image is not updated on map or on allocate page. 

**Map view:**
profile pic problem
**Allocation page view:**
profile pic problem2

Tried this in Firefox and Chrome.

### PR DESCRIPTION
**Pull request by f1lander**
fixes #417 

### problem
the `profile.avatar` is for some reason an empty string that's the reason why the map page is not loading the pfp.

image

### Solution

A non-empty string validation for the avatar value.

```
const p = profile ?? user?.profile;
let avatar = p?.avatar;
if (avatar === '') avatar = user?.profile?.avatar;
```
Screen Shot 2022-01-25 at 00 20 37

PS. @zashton address the `profile.updated_at` is not updated like the `user.updated_at` 
image

@exrhizo it could be something about the recoil state profile object request here? 
image

### CODE REVIEW

**Comment by zashton** [comment]
tried to clear the token gifts historical cache for circle on the backend upon pfp update, seem unrelated to this issue

File: src/components/ApeAvatar/ApeAvatar.tsx [hunk 1]
```diff
@@ -19,7 +19,9 @@ export const ApeAvatar = ({
 }) => {
   // TODO: simplify so all: <ApeAvatar path={getAvatarPath(p?.avatar)} />
   const p = profile ?? user?.profile;
-  const avatarPath = getAvatarPathWithFallback(p?.avatar, user?.name);
+  let avatar = p?.avatar;
+  if (avatar === '') avatar = user?.profile?.avatar;
```
Comment (levity) [inline src/components/ApeAvatar/ApeAvatar.tsx:23]:
```suggestion
  const avatar = p?.avatar || user?.profile?.avatar;
```

File: src/recoilState/map.ts [hunk 2]
```diff
@@ -181,9 +181,13 @@ export const rMapGraphData = selector<GraphData>({
             `Missing user of circle = ${epoch.circle_id} in rMapGraphData at ${profile.address}`
           );
 
+          const p = profile ?? user?.profile;
+          let avatar = p?.avatar;
+          if (avatar === '') avatar = user?.profile?.avatar;
```
Comment (levity) [inline src/recoilState/map.ts:186]:
```suggestion
          const avatar = p?.avatar || user?.profile?.avatar;
```

**Review by levity — CHANGES_REQUESTED** [review]
do these more concise versions look good to you?

File: src/components/ApeAvatar/ApeAvatar.tsx [hunk 3]
```diff
@@ -19,7 +19,9 @@ export const ApeAvatar = ({
 }) => {
   // TODO: simplify so all: <ApeAvatar path={getAvatarPath(p?.avatar)} />
   const p = profile ?? user?.profile;
```
Comment (levity) [inline src/components/ApeAvatar/ApeAvatar.tsx:21]:
```suggestion
```

**Comment by exrhizo** [comment]
I think you are right edax, I can look at it tomorrow, 
if `rUserProfileMap` doesn't have avatars for some reason then that would cause this...
maybe because it uses `createFakeProfile(assertDef(us.first()))`

This is all convoluted, but the source of this sort of thing is that the profile may be missing for a given user and addresses can be changed.

This is one place that refactoring with the database to force consistency would be helpful

File: src/components/ApeAvatar/ApeAvatar.tsx (hunk 1 above)
Comment (f1lander) [reply src/components/ApeAvatar/ApeAvatar.tsx:23]: this is clever, thanks! I was falling asleep 😪

**Review by levity — DISMISSED** [review]

**Review by exrhizo — APPROVED** [review]
LGTM
