### PR TITLE
Bug/671/show errors nominate modal

### LINKED ISSUE #671: BUG: Show error in nominate form when ETH address invalid
**Summary:**
When nominating a user there is no appropriate error text when the eth address is invalid 

1. **What is actually happening:**
No error is presented, but Nominate Member button is disabled

3. **What should be happening:**
There should be an error inline in the form

4. **Steps to recreate:**
Go to nominate a user, input an invalid ETH address

5. **Screenshots/GIF/Video recording**
image

### PR DESCRIPTION
**Pull request by sshmm**
update NomianteModal to show errors to fix  #671  and use ui library with stitches

Update NewNominationModal to use ui components like Modal and Form. Change the styling from make Styles to stitches. Add FormLabel in ui library to use as labels for input fields.

### CODE REVIEW

File: src/ui/index.ts [hunk 1]
```diff
@@ -10,6 +10,8 @@ export * from './Panel/Panel';
 export * from './SvgIcon/SvgIcon';
 export * from './Text/Text';
 export * from './TextField/TextField';
+export * from './FormLabel/FormLabel';
```
Comment (levity) [inline src/ui/index.ts:13]: please keep this file in alphabetical order

File: src/pages/VouchingPage/NewNominationModal.tsx [hunk 2]
```diff
@@ -58,70 +40,116 @@ export const NewNominationModal = ({
           : ''
       }`
     : '';
+  type NominateFormValues = {
```
Comment (levity) [inline src/pages/VouchingPage/NewNominationModal.tsx:43]: Types should be defined at the top-level of a file, not inside a component

File: src/pages/VouchingPage/NewNominationModal.tsx [hunk 3]
```diff
@@ -58,70 +40,116 @@ export const NewNominationModal = ({
...
+    name: string;
+    address: string;
+    description: string;
+  };
+  const intialValues = {
```
Comment (levity) [inline src/pages/VouchingPage/NewNominationModal.tsx:48]:
```suggestion
  const initialValues = {
```

File: src/pages/VouchingPage/NewNominationModal.tsx [hunk 4]
```diff
@@ -58,70 +40,116 @@ export const NewNominationModal = ({
...
-          inputProps={{
-            maxLength: 280,
-          }}
-          fullWidth
-        />
-      </div>
-    </FormModal>
+    <Modal title="Nominate New Member" open={visible} onClose={onClose}>
+      <Form nominate onSubmit={handleSubmit(onSubmit)}>
+        <Text>{nominateDescription}</Text>
```
Comment (levity) [inline src/pages/VouchingPage/NewNominationModal.tsx:72]: Please add `lineHeight: 'normal'` to the styles here so that the text does not look so crowded

File: src/ui/Form.tsx [hunk 5]
```diff
@@ -1,2 +1,20 @@
 import { styled } from 'stitches.config';
-export const Form = styled('form', {});
+export const Form = styled('form', {
+  variants: {
+    nominate: {
```
Comment (levity) [inline src/ui/Form.tsx:4]: In this case, rather than creating a new `Form` component, I would suggest using a regular `<form>` tag without any styles, and just adding styles to a `<Box>` that's either a parent or child of `<form>`. There's no advantage to coupling these styles to the `<form>` tag.

File: src/ui/Form.tsx [hunk 6]
```diff
@@ -1,2 +1,20 @@
...
+        display: 'flex',
+        flexDirection: 'column',
+        alignItems: 'center',
+        backgroundColor: 'white',
+        width: '100%',
+        borderRadius: 8,
+        padding: '0 0 $lg',
+        overflowY: 'auto',
+        maxHeight: '100vh',
+        maxWidth: '648px',
```
Comment (levity) [inline src/ui/Form.tsx:16]: you should be able to avoid hardcoding a value like this, and instead rely on the fact that `Modal` already has a maxWidth set.

File: src/ui/Box/Box.tsx [hunk 7]
```diff
@@ -1,5 +1,36 @@
...
+        width: '100%',
+      },
+    },
+    errors: {
+      true: {
+        display: 'flex',
+        flexDirection: 'column',
+        justifyContent: 'center',
+        margin: 0,
+        minHeight: 45,
```
Comment (levity) [inline src/ui/Box/Box.tsx:19]: not sure what this accomplishes

**Review by levity — CHANGES_REQUESTED** [review]
Thanks for submitting this!

In general, my feedback for this is that many of the styles in variants should instead be added directly to their components in `NewNominationModal` using the `css` prop. Variants should only be created when a group of styles is meant to be reused in different contexts. 

So the variants named `nominate` should definitely just be added directly in NewNominationModal, since they're specific to that component's needs. Many of the other ones should be as well, like `input` and `errors` in Box. They happen to be useful for wrapping inputs and errors in NewNominationModal, but it's unlikely that they'll be used in exactly the same way elsewhere. Even if it seems a little repetitive, it's better to err on the side of defining styles inline, at least while our design system is still in flux.

File: src/ui/Form.tsx (hunk 5 above)
Comment (sshmm) [reply src/ui/Form.tsx:4]: @levity I am not using a new form component. I am using ui/Form that already exists should I change that?

File: src/ui/Box/Box.tsx (hunk 7 above)
Comment (sshmm) [reply src/ui/Box/Box.tsx:19]: it's meant to center then input and the label, keep them in a column..

File: src/ui/Form.tsx (hunk 5 above)
Comment (levity) [reply src/ui/Form.tsx:4]: ah, i see. yes, i think it's ok to keep using this, but putting the styles on the tag in the NewNominateModal rather than creating the variant here.

File: src/ui/Box/Box.tsx (hunk 7 above)
Comment (levity) [reply src/ui/Box/Box.tsx:19]: i mean minHeight specifically. were you trying to prevent the form from resizing when errors appear/disappear?

Comment (sshmm) [reply src/ui/Box/Box.tsx:19]: I tried to replicate the old styling.But you are right, this should be removed because it make the error text and textarea above when resizing the page to smaller heights

**Comment by sshmm** [comment]
> Thanks for submitting this!
> 
> In general, my feedback for this is that many of the styles in variants should instead be added directly to their components in `NewNominationModal` using the `css` prop. Variants should only be created when a group of styles is meant to be reused in different contexts.
> 
> So the variants named `nominate` should definitely just be added directly in NewNominationModal, since they're specific to that component's needs. Many of the other ones should be as well, like `input` and `errors` in Box. They happen to be useful for wrapping inputs and errors in NewNominationModal, but it's unlikely that they'll be used in exactly the same way elsewhere. Even if it seems a little repetitive, it's better to err on the side of defining styles inline, at least while our design system is still in flux.

@levity thanks for the through review. I applied these suggestion in 5a5e0c98b07a3fcd1d344a26c1983d8ad6101567

File: src/pages/VouchingPage/NewNominationModal.tsx [hunk 8]
```diff
@@ -59,69 +52,209 @@ export const NewNominationModal = ({
...
+                required: 'Name must be at least 3 characters long.',
+                minLength: {
+                  value: 3,
+                  message: 'Name must be at least 3 characters long.',
+                },
+              }}
+              control={control}
+              render={({ field }) => (
+                <TextField
+                  css={{ height: '48px', width: '100%' }}
```
Comment (levity) [inline src/pages/VouchingPage/NewNominationModal.tsx]: instead of `48px` you can use the `$2xl` size token here

File: src/pages/VouchingPage/NewNominationModal.tsx [hunk 9]
```diff
@@ -59,69 +52,209 @@ export const NewNominationModal = ({
...
+                fontSize: '$4',
+                fontFamily: 'Inter',
+                fontWeight: '$bold',
+                textAlign: 'center',
+                m: '0 0 $sm',
+              }}
+            >
+              Name
+            </FormLabel>
+            <Controller
```
Comment (levity) [inline src/pages/VouchingPage/NewNominationModal.tsx]: Can you use the `useController` hook instead? It's a lot nicer IMO because the form logic is more separated from presentation, and also there's less nesting of components. Check out what we did in VaultsPage/CreateForm for an example.

File: src/pages/VouchingPage/NewNominationModal.tsx [hunk 10]
```diff
@@ -59,69 +52,209 @@ export const NewNominationModal = ({
...
+              'grid-column': '1 / -1',
+              display: 'flex',
+              flexDirection: 'column',
+              alignItems: 'center',
+              width: '100%',
+            }}
+          >
+            <FormLabel
+              htmlFor="description"
+              css={{
```
Comment (levity) [inline src/pages/VouchingPage/NewNominationModal.tsx:175]: Even though this isn't a variant anymore, it is still the same the 3 times it's used in this file, so it would be good to pull it out into a variable to reduce duplication.

**Comment by sshmm** [comment]
@levity  I added some margin between the Nomination description and the inputs and above the description input to match the previous design.
Separated the labels and inputs of name and address into different rows so that the address input box won't be pushed down on resizing to very narrow width
image

**Review by levity — CHANGES_REQUESTED** [review]
Thanks for the latest updates! I have a few more suggestions.

File: src/pages/VouchingPage/NewNominationModal.tsx (hunk 9 above)
Comment (sshmm) [reply src/pages/VouchingPage/NewNominationModal.tsx]: I updated it to use useController with zodresolver instead of passing "rules" to useController

File: src/pages/VouchingPage/NewNominationModal.tsx (hunk 10 above)
Comment (sshmm) [reply src/pages/VouchingPage/NewNominationModal.tsx]: added labelStyles const

File: src/pages/VouchingPage/NewNominationModal.tsx [hunk 11]
```diff
@@ -1,33 +1,30 @@
...
-  gridAllColumns: {
-    gridColumn: '1/-1',
-  },
-}));
+type NominateFormValues = {
+  name: string;
+  address: string;
+  description: string;
+};
+const intialValues = {
```
[the remark this answers is not in the document]
Comment (sshmm) [reply src/pages/VouchingPage/NewNominationModal.tsx]: I removed this cont and passed default values to useController directly

**Review by levity — APPROVED** [review]

**Comment by levity** [comment]
nice work @sshmm!
