### PR TITLE
fix incorrect label for Create Epoch button

### LINKED ISSUE #1082: Create Epoch button is mislabeled Add Contributor
image

### PR DESCRIPTION
**Pull request by CryptoGraffe**
Fixes #1082 by making the button label a prop on `EmptyTable` reusable component

### CODE REVIEW

**Review by crabsinger — APPROVED** [review]

File: src/pages/AdminPage/components.tsx [hunk 1]
```diff
@@ -536,6 +538,7 @@ export const EpochsTable = ({
               <Table.Cell key={`empty-epochs-table-view`} colSpan={4}>
                 <EmptyTable
                   content="You don’t have any epochs scheduled"
+                  createLabel={'Create Epoch'}
```
Comment (levity) [inline src/pages/AdminPage/components.tsx:541]:
```suggestion
                  createLabel="Create Epoch"
```

**Review by levity — APPROVED** [review]
