### PR TITLE
Distribution page UI design

### LINKED ISSUE #813: add Gift Circle / Fixed Payments UI to Submit Distribution page
- when fixed payments are disabled
  - show only one vault selector & amount form
  - show the "fixed payments are disabled"  message in the place of the other form
- if the fixed payment token doesn't match any vault you control
  - form fields are disabled, vault dropdown shows "No vault"
  - button is Export CSV instead of Submit Distribution
- when fixed payments are enabled
  - show Gift Circle form & Fixed Payment form
    - the fixed payment's vault selector is disabled, since it's hardcoded to the fixed payment token type from circle settings
    - the budget amount input is also disabled and fixed to the sum of all users' fixed payments in the circle
  - when the fixed payment token is the same as the gift circle token
    - show only a single submit button, because there's only one transaction necessary
  - if the tokens are different
    - show two submit buttons
      - each one starts a separate transaction flow
    - after submission
      - button becomes a "View on Etherscan" button
      - display summary of distribution instead of form
      - 1 Backlink
        - same as after submission
- form validation for both forms
  - if the vault doesn't have enough funds for the specified amount, show error & disable button
- combined data table
  - show columns for both the gift circle and fixed payments column
  - if they're the same token, show a column of summed values
- backend data change
  - Store in the distribution table the type(s) it was for: gift circle, fixed payments, or both
    - because we can't just infer from the current fixed payment token type in circle settings -- that could change after distribution
    - store the gift amount and fixed amount
- loading the page after 1 or 2 distributions have been submitted
  - same as after submission
  - use the submitted distribution data for the forms and the data table

### LINKED ISSUE #1122: Balance available doesn't update on distributions screen
**Summary:**

1. **What is actually happening:**

After a deposit the Available amount reflects the vault balance before
submitting a distribution

2. **What should be happening:**

The balance should reflect the amount available in the vault after the
distribution is created

3. **Steps to recreate:**

  - create a vault in the org containing the sports circle
  - deposit some funds
  - create a distribution for the epoch in the sports circle
  - observe that the balance doesn't update until the page refreshes

4. **Screenshots/GIF/Video recording**
Screenshots/video recordings of the issue are very helpful as well. Checking the browser's console for errors also provides developers with helpful debugging information. See [this guide](https://balsamiq.com/support/faqs/browserconsole/) for details on opening the develop console.

### PR DESCRIPTION
**Pull request by zashton**
fixes #813 
fixes #1122 

image

https://www.figma.com/file/L4oZwYVUdpgacZtwipGaYe/App-1.5?node-id=4680%3A11831

### CODE REVIEW

File: src/lib/merkle-distributor/index.ts [hunk 1]
```diff
@@ -30,11 +30,16 @@ export const createDistribution = (
   giftAmount: BigNumber,
   previousDistribution?: Partial<MerkleDistributorInfo>
 ): MerkleDistributorInfo => {
-  const totalGive = Object.values(gifts).reduce((t, v) => t + v);
-  let balances = Object.keys(gifts).map(address => ({
-    address,
-    earnings: giftAmount.mul(gifts[address]).div(totalGive),
-  }));
+  let balances: Balance[] = [];
```
Comment (levity) [inline src/lib/merkle-distributor/index.ts:33]: wrapping this whole thing in an if-clause and using `push` isn't necessary--all you need to do is add a default value to `reduce`:
```js
  const totalGive = Object.values(gifts).reduce((t, v) => t + v, 0);
```

File: src/pages/DistributionsPage/DistributionForm.tsx [hunk 2]
```diff
@@ -292,259 +300,374 @@ export function DistributionForm({
...
-            {isCombinedDistribution() ? (
-              <span>
+            </Box>
+          </TwoColumnLayout>
+        </Panel>
+        {(fixedDist || circleDist) && <Summary distribution={circleDist} />}
+        <Flex css={{ justifyContent: 'center', mt: '$xl', mb: '$xl' }}>
+          {!circleDist ? (
+            isCombinedDistribution() ? (
+              <Text css={{ fontSize: '$small', lineHeight: '$xtaller' }}>
```
Comment (levity) [inline src/pages/DistributionsPage/DistributionForm.tsx:407]: please use padding or fixed-height for the div here, instead of adding this one-off token `$xtaller` to the stitches theme

File: src/stitches.config.ts [hunk 3]
```diff
@@ -165,6 +165,7 @@ export const {
       tall: 1.625,
       tall2: 1.75,
       taller: '2',
+      xtaller: '3.5',
```
Comment (levity) [inline src/stitches.config.ts:168]: remove

File: src/pages/DistributionsPage/DistributionForm.tsx [hunk 4]
```diff
@@ -292,259 +300,374 @@ export function DistributionForm({
...
   );
 }
+
+const Summary = ({
+  distribution,
+}: {
+  distribution: EpochDataResult['distributions'][0] | undefined;
+}) => {
+  return (
+    <Flex
```
Comment (levity) [inline src/pages/DistributionsPage/DistributionForm.tsx:631]: if `!distribution`, should we just return null instead of an empty Flex?

File: src/pages/DistributionsPage/DistributionForm.tsx [hunk 5]
```diff
@@ -292,259 +300,374 @@ export function DistributionForm({
...
+            ) : (
+              <Button
+                type="button"
+                color="primary"
+                outlined
+                size="large"
+                fullWidth
+                onClick={async () => {
+                  // use the authed api to download the CSV
+                  if (epoch.number) {
```
Comment (levity) [inline src/pages/DistributionsPage/DistributionForm.tsx:600]: if this doesn't work unless an epoch number is present, we probably just shouldn't show the button at all if it's missing. i see it was like this already before your changes, i should have caught it earlier

File: src/pages/DistributionsPage/DistributionForm.tsx [hunk 6]
```diff
@@ -292,259 +300,374 @@ export function DistributionForm({
...
+                          )}
+                        </>
+                      )}
+                    />
+                  </FormControl>
+                </Box>
+                <Box css={{ width: '100%' }}>
                   <Controller
-                    name="selectedVaultId"
+                    name={'amount'}
```
Comment (levity) [inline src/pages/DistributionsPage/DistributionForm.tsx:520]:
```suggestion
                    name="amount"
```

File: src/pages/DistributionsPage/DistributionForm.tsx [hunk 7]
```diff
@@ -292,259 +300,374 @@ export function DistributionForm({
...
                 fullWidth
               >
                 {sufficientGiftTokens
                   ? submitting
-                    ? 'Submitting...'
-                    : 'Submit Distribution'
-                  : 'Insufficient Tokens'}
+                    ? `Submitting...`
+                    : `Submit ${giftVaultSymbol} Vault Distribution`
+                  : `Insufficient Tokens`}
```
Comment (levity) [inline src/pages/DistributionsPage/DistributionForm.tsx:424]:
```suggestion
                    ? 'Submitting...'
                    : `Submit ${giftVaultSymbol} Vault Distribution`
                  : 'Insufficient Tokens'}
```

File: src/pages/DistributionsPage/DistributionForm.tsx [hunk 8]
```diff
@@ -292,259 +300,374 @@ export function DistributionForm({
...
+                      const v = findVault({ symbol: giftVaultSymbol });
+                      if (v) return v.decimals;
+                      return 0;
+                    })()}
+                    type="number"
+                    error={!!error}
+                    value={circleDist ? circleDist.gift_amount : value}
+                    disabled={submitting || !!circleDist || vaults.length === 0}
+                    max={Number(maxGiftTokens)}
+                    prelabel={'Budget Amount'}
```
Comment (levity) [inline src/pages/DistributionsPage/DistributionForm.tsx:381]:
```suggestion
                    prelabel="Budget Amount"
```

File: src/pages/DistributionsPage/DistributionForm.tsx [hunk 9]
```diff
@@ -292,259 +300,374 @@ export function DistributionForm({
...
+                      )}
+                    </>
+                  )}
+                />
+              </FormControl>
+            </Box>
+            <Box css={{ width: '100%' }}>
               <Controller
-                name="selectedVaultId"
+                name={'amount'}
```
Comment (levity) [inline src/pages/DistributionsPage/DistributionForm.tsx:362]:
```suggestion
                name="amount"
```

File: src/pages/DistributionsPage/DistributionForm.tsx [hunk 10]
```diff
@@ -292,259 +300,374 @@ export function DistributionForm({
...
-            <FormControl fullWidth>
-              <Box css={vaultInputStyles}>Select Vault</Box>
+        <Panel css={{ padding: '16px', minHeight: '147px' }}>
+          <Text h2 css={headerStyle}>
+            Gift Circle
+          </Text>
+          <TwoColumnLayout css={{ pt: '$md' }}>
+            <Box css={{ width: '100%' }}>
+              <FormControl fullWidth>
+                <Controller
```
Comment (levity) [inline src/pages/DistributionsPage/DistributionForm.tsx:312]: just FYI, react-hook-form also has a `useController` hook that you can use instead of this component. I think it's nicer because it produces less nesting. no need to change it in this PR though.

File: src/pages/DistributionsPage/AllocationsTable.tsx [hunk 11]
```diff
@@ -51,53 +66,106 @@ export const AllocationsTable = ({
...
+          justifyContent: 'space-between',
+          mt: '$lg',
+        }}
+      >
+        <Link
+          css={{ color: '$primary' }}
+          target="_blank"
+          href="https://docs.coordinape.com/get-started/compensation/paying-your-team"
+        >
+          Paying Your Team Documentation
```
Comment (levity) [inline src/pages/DistributionsPage/AllocationsTable.tsx:165]:
```suggestion
          Documentation: Paying Your Team 
```

**Review by levity — CHANGES_REQUESTED** [review]
Looking good so far! See below.

File: src/pages/DistributionsPage/DistributionForm.tsx (hunk 10 above)
Comment (zashton) [reply src/pages/DistributionsPage/DistributionForm.tsx:314]: created an issue for this
https://github.com/coordinape/coordinape/issues/1168

**Comment by levity** [comment]
@zashton there are still a few more open comments from my review; maybe you missed them because DistributionForm's diff is collapsed by default in Github?

File: src/pages/DistributionsPage/DistributionForm.tsx (hunk 4 above)
Comment (zashton) [reply src/pages/DistributionsPage/DistributionForm.tsx:648]: it would look like this if its a non combined distribution without the Flex box

image

File: src/pages/DistributionsPage/DistributionForm.tsx (hunk 5 above)
Comment (zashton) [reply src/pages/DistributionsPage/DistributionForm.tsx]: i've updated it to not show but had to leave the `if (epoch.number)` inside the onclick not sure why typescript is showing an issue

File: src/pages/DistributionsPage/DistributionForm.tsx (hunk 4 above)
Comment (zashton) [reply src/pages/DistributionsPage/DistributionForm.tsx:648]: > @zashton there are still a few more open comments from my review; maybe you missed them because DistributionForm's diff is collapsed by default in Github?

yeah my bad for missing, some of the review got hidden by default. Have added the changes
