### PR TITLE
Error handling improvements for #917 #916 #902 #878 #875 #874

### LINKED ISSUE #874: Discord Daily Update error for circle #1436: {"message":"Unknown Webhook","code":10015}
Sentry Issue: [APP-N0](https://sentry.io/organizations/coordinape/issues/3115174876/?referrer=github_integration)

```
Discord Daily Update error for circle #1436: {"message":"Unknown Webhook","code":10015}
```

### LINKED ISSUE #875: graphql error:  Authentication hook unauthorized this request
Sentry Issue: [APP-W7](https://sentry.io/organizations/coordinape/issues/3252288792/?referrer=github_integration)

```
graphql error:  Authentication hook unauthorized this request
```

### LINKED ISSUE #878: Failed to login [object Object]
Sentry Issue: [APP-BC](https://sentry.io/organizations/coordinape/issues/2823503459/?referrer=github_integration)

```
Failed to login [object Object]
```

### LINKED ISSUE #902: TypeError: Cannot use 'in' operator to search for 'message' in problem loading circle - the circle we tried ...
Sentry Issue: [APP-WE](https://sentry.io/organizations/coordinape/issues/3253264155/?referrer=github_integration)

```
TypeError: Cannot use 'in' operator to search for 'message' in problem loading circle - the circle we tried to load (5) could not be found by current user
  at reportException (utils/reporting.ts:15:40)
  at None (hooks/useRecoilLoadCatch.ts:68:15)
```

This code should do instanceof string and handle that properly, and we should do a sweep for `throw 'string'`

### LINKED ISSUE #916: Error: Failed to get a login token
Sentry Issue: [APP-XR](https://sentry.io/organizations/coordinape/issues/3273408641/?referrer=github_integration)

```
Error: Failed to get a login token
  at reportException (utils/reporting.ts:25:36)
  at None (hooks/useRecoilLoadCatch.ts:67:15)
```

### LINKED ISSUE #917: For circle id 1563,  2022-05-17T04:00:00.000Z overlaps with the another epoch: existing epoch id:...
Sentry Issue: [APP-SY](https://sentry.io/organizations/coordinape/issues/3203193583/?referrer=github_integration)

```
For circle id 1563,  2022-05-17T04:00:00.000Z overlaps with the another epoch: existing epoch id: 4945, start: 2022-05-17T04:00:00+00:00, end: 2022-05-24T04:00:00+00:00
```

### PR DESCRIPTION
**Pull request by CryptoGraffe**
Fixes #917 
Fixes #916
Fixes #902
Fixes #878
Fixes #875 
Fixes #874

Improving error handling and ignoring certain classes of errors to clean up Sentry.

### CODE REVIEW

**Review by META-DREAMER — DISMISSED** [review]

File: scripts/generate_zeus.sh [hunk 1]
```diff
@@ -31,14 +31,17 @@ function generate() {
   if [[ "$PLATFORM" == "OSX" || "$PLATFORM" == "BSD" ]]; then
     sed -i "" 's,bigint"]:any,bigint"]:number,g' "$TMP_GEN_PATH"/zeus/index.ts
     sed -i "" 's,bigint"]:unknown,bigint"]:number,g' "$TMP_GEN_PATH"/zeus/index.ts
+    sed -i "" 's/console\.error(response)/\/\/ eslint-disable-next-line no-console\nconsole\.info(JSON\.stringify(response))/g' "$TMP_GEN_PATH"/zeus/index.ts
   elif [ "$PLATFORM" == "LINUX" ]; then
     sed -i 's,bigint"]:any,bigint"]:number,g' "$TMP_GEN_PATH"/zeus/index.ts
     sed -i 's,bigint"]:unknown,bigint"]:number,g' "$TMP_GEN_PATH"/zeus/index.ts
+    sed -i 's/console\.error(response)/\/\/ eslint-disable-next-line no-console\nconsole\.info(JSON\.stringify(response))/g' "$TMP_GEN_PATH"/zeus/index.ts
```
Comment (topocount) [inline scripts/generate_zeus.sh:38]:
```suggestion
    sed -i 's/console\.error(response)/\/\/ eslint-disable-next-line no-console\nconsole\.info(JSON\.stringify(response, null, 2))/g' "$TMP_GEN_PATH"/zeus/index.ts
```

**Review by topocount — DISMISSED** [review]

**Comment by topocount** [comment]
@CryptoGraffe I'll rubber stamp this post-rebase

**Comment by CryptoGraffe** [comment]
@topocount rebased!

**Review by zashton — APPROVED** [review]
