### PR TITLE
Fix for duplicate address issue

### LINKED ISSUE #833: Users with same address in the same circle
**Summary:**

1. **What is actually happening:**
 Users with the same address that are not soft deleted are appearing in the same circle

2. **What should be happening:**
There shouldn't be duplicated address appearing in the same circle

3. **Steps to recreate:**
a. Create a nominee
b. Create a new user with the same address but different name
c. Give sufficient vouches to that nominee
d. Nominee gets created into a user and two users with the same address are in the same circle

### PR DESCRIPTION
**Pull request by zashton**
Fixes #833

### Test Plan
1. Create a nominee
2. Create a user with the same address but different name (or update a user to the same address)
3. Make sure nomination has ended and you cannot vouch for the user anymore
4. Ensure `checkNominee` cron job is running
5. Check for DB conflicts run:

```sql 
SELECT address, circle_id, deleted_at
FROM public.users
group by address, circle_id, deleted_at having  count(*) > 1;
```

### CODE REVIEW

**Comment by zashton** [comment]
> can you also create a database migration to add a uniqueness constraint for `(address, circle_id, deleted_at)`?

yeap, def could add that

**Comment by zashton** [comment]
just added them, to check for db conflicts

```sql SELECT address, circle_id, deleted_at
FROM public.users
group by address, circle_id, deleted_at having  count(*) > 1;
```

File: hasura/migrations/default/1651000685281_alter_table_public_users_add_unique_address_circle_id_deleted_at/up.sql [hunk 1]
```diff
@@ -0,0 +1 @@
+alter table "public"."users" add constraint "users_address_circle_id_deleted_at_key" unique ("address", "circle_id", "deleted_at");
```
Comment (topocount) [inline hasura/migrations/default/1651000685281_alter_table_public_users_add_unique_address_circle_id_deleted_at/up.sql:1]: I tried to implement logic in createUser that "undeletes" soft-deleted users, and therefore this constraint should just require the `address` and `circle_id` columns. Is the logic not airtight enough to do that, or is existing production data preventing this? I think having a bunch of deleted users in a circle with the same address will make for some messy situations.

Comment (zashton) [reply hasura/migrations/default/1651000685281_alter_table_public_users_add_unique_address_circle_id_deleted_at/up.sql:1]: yeah prior to your undelete feature there were cases of creating a new user after soft deleting one with the same address.The soft deleted users can't be hard deleted because of token_gifts fk constraints

File: api/hasura/actions/adminUpdateUser.ts [hunk 2]
```diff
@@ -91,6 +91,21 @@ async function handler(req: VercelRequest, res: VercelResponse) {
         },
       },
     ],
+    update_nominees: [
```
Comment (topocount) [inline api/hasura/actions/adminUpdateUser.ts:94]: nice

**Review by topocount — APPROVED** [review]
send it!
