### PR TITLE
fix bug: Allocation countdown

### LINKED ISSUE #1719: Allocation countdown says "3hrs, 60 minutes"
**Summary:**
"3hrs, 60 minutes" is a little bit strange.

1. **What should be happening:**
Normally you would see "4hrs" or "3hrs, 59 minutes".

2. **Steps to recreate:**
Go to circles/##/givebeta

4. **Screenshots/GIF/Video recording**
Screenshot 2022-11-30 at 21 00 37

### PR DESCRIPTION
**Pull request by MooSeMoos**
## Motivation and Context

resolves #1719 

## Description

-Allow time of the created Epochs to be shown correctly 

## Test and Deployment Plan

open any circle --> create an epoch --> set a time that you like -->check Allocation countdown in (Epoch Overview, give)

## Screenshots (if appropriate):

Screenshot from 2022-12-07 15-53-36
Screenshot from 2022-12-07 15-53-30

## Reviewers

@levity 

## Related Issue

#1719

### CODE REVIEW

File: src/lib/time.ts [hunk 1]
```diff
@@ -4,6 +4,6 @@ import { DateTime } from 'luxon';
 export const epochTimeUpcoming = (startDate: DateTime) => {
   return startDate
     .diffNow(['days', 'hours', 'minutes'])
-    .toHuman({ unitDisplay: 'short', notation: 'compact' })
+    .toFormat("d' days, 'h' hr, 'm' mins'")
```
Comment (levity) [inline src/lib/time.ts:7]: Please create `src/lib/time.test.ts` and add some unit tests for the examples shown in #1719, as well as some larger time values that are greater than 1 day.

Comment (MooSeMoos) [reply src/lib/time.ts]: done

**Review by levity — APPROVED** [review]
Nice work. I edited the tests to make them a bit more compact. It's ok to have multiple simple assertions in one test, since Jest will tell us which line has failed if there's a failure.
